spring.application.name=backend
server.port=8080

# Configuracion de la Base de Datos (Se reemplazara la IP por la del servidor DATA en AWS)
# Esta IP 'data-server-ip' es referencial para la arquitectura Lift & Shift.
spring.datasource.url=jdbc:mysql://data-server-ip:3306/innovatech?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactivar cache para desarrollo
spring.cache.type=none

# SOLUCION: Evitar colision de Beans al inicializar el contexto
spring.main.allow-bean-definition-overriding=true
springdoc.swagger-ui.enabled=false
springfox.documentation.swagger-ui.enabled=false